<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JustData.Application\JustData.Application.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalJustyBaseLibraries)' == 'true'">
    <ProjectReference Include="$(JustyBaseLocalNetezzaSqlParserProject)" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalJustyBaseLibraries)' != 'true'">
    <PackageReference Include="JustyBase.NetezzaSqlParser" />
  </ItemGroup>
</Project>
